"""initial_schema

Revision ID: 204a33832988
Revises:
Create Date: 2026-10-07 14:41:25.747212

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "204a33832988"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("daily_capacity_hours", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_members_project_id"), "members", ["project_id"], unique=False)
    op.create_table(
        "progress_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=100), nullable=False),
        sa.Column("previous_status", sa.String(length=50), nullable=True),
        sa.Column("new_status", sa.String(length=50), nullable=False),
        sa.Column("evidence_notes", sa.Text(), nullable=False),
        sa.Column("recorded_by", sa.String(length=255), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_progress_history_project_id"), "progress_history", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_progress_history_recorded_at"), "progress_history", ["recorded_at"], unique=False
    )
    op.create_index(
        op.f("ix_progress_history_task_id"), "progress_history", ["task_id"], unique=False
    )
    op.create_table(
        "project_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("target_completion_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version", name="uq_project_plan_version"),
    )
    op.create_index(
        op.f("ix_project_plans_is_active"), "project_plans", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_project_plans_project_id"), "project_plans", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_project_plans_version"), "project_plans", ["version"], unique=False)
    op.create_table(
        "risk_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("risk_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_events_detected_at"), "risk_events", ["detected_at"], unique=False
    )
    op.create_index(op.f("ix_risk_events_project_id"), "risk_events", ["project_id"], unique=False)
    op.create_index(op.f("ix_risk_events_risk_type"), "risk_events", ["risk_type"], unique=False)
    op.create_table(
        "decision_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=True),
        sa.Column("decision_type", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.String(length=255), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("decided_by", sa.String(length=255), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["project_plans.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_records_project_id"), "decision_records", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_decision_records_recorded_at"), "decision_records", ["recorded_at"], unique=False
    )
    op.create_table(
        "plan_dependencies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("predecessor_id", sa.String(length=100), nullable=False),
        sa.Column("successor_id", sa.String(length=100), nullable=False),
        sa.Column("dep_type", sa.String(length=50), nullable=False),
        sa.Column("lag_days", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["project_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plan_dependencies_plan_id"), "plan_dependencies", ["plan_id"], unique=False
    )
    op.create_table(
        "plan_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("estimated_hours", sa.Float(), nullable=False),
        sa.Column("assigned_to_id", sa.String(length=36), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["plan_id"], ["project_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "task_id", name="uq_plan_task_id"),
    )
    op.create_index(op.f("ix_plan_tasks_plan_id"), "plan_tasks", ["plan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plan_tasks_plan_id"), table_name="plan_tasks")
    op.drop_table("plan_tasks")
    op.drop_index(op.f("ix_plan_dependencies_plan_id"), table_name="plan_dependencies")
    op.drop_table("plan_dependencies")
    op.drop_index(op.f("ix_decision_records_recorded_at"), table_name="decision_records")
    op.drop_index(op.f("ix_decision_records_project_id"), table_name="decision_records")
    op.drop_table("decision_records")
    op.drop_index(op.f("ix_risk_events_risk_type"), table_name="risk_events")
    op.drop_index(op.f("ix_risk_events_project_id"), table_name="risk_events")
    op.drop_index(op.f("ix_risk_events_detected_at"), table_name="risk_events")
    op.drop_table("risk_events")
    op.drop_index(op.f("ix_project_plans_version"), table_name="project_plans")
    op.drop_index(op.f("ix_project_plans_project_id"), table_name="project_plans")
    op.drop_index(op.f("ix_project_plans_is_active"), table_name="project_plans")
    op.drop_table("project_plans")
    op.drop_index(op.f("ix_progress_history_task_id"), table_name="progress_history")
    op.drop_index(op.f("ix_progress_history_recorded_at"), table_name="progress_history")
    op.drop_index(op.f("ix_progress_history_project_id"), table_name="progress_history")
    op.drop_table("progress_history")
    op.drop_index(op.f("ix_members_project_id"), table_name="members")
    op.drop_table("members")
    op.drop_table("projects")
    # ### end Alembic commands ###
